Upates Ruby version for the GitHub Actions
Versions 3.1.x are no longer available on GitHub Actions, The following
error is being thrown in the GitHub Actions logs:

  Error: Error: Unavailable version 3.1.7 for ruby on ubuntu-24.04

So, all the actions that are using Ruby 3.1 are hereby updated to use
Ruby 3.2 instead.